### ISSUE TITLE
直接运行 rpc server 例子报错

### ISSUE THREAD

**Issue by liuzhuogood** [so1n/rap#4]
RuntimeError: Can not parse <class 'inspect._empty'> origin type

**Comment by so1n** [comment]
README.md正在编写中, 请尝试运行exmaple的例子

**Comment by so1n** [comment]
> RuntimeError: Can not parse <class 'inspect._empty'> origin type

README.md正在编写中, 请尝试运行exmaple的例子

**Comment by so1n** [comment]
> > RuntimeError: Can not parse <class 'inspect._empty'> origin type
> 
> README.md正在编写中, 请尝试运行exmaple的例子

README.md已经更新
